export const fallbackQuestions = [
  {
    question: "What is 2+2?",
    correct_answer: "4",
    incorrect_answers: ["3", "5", "6"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 7 x 3?",
    correct_answer: "21",
    incorrect_answers: ["24", "18", "27"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is the square root of 64?",
    correct_answer: "8",
    incorrect_answers: ["6", "7", "9"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 100 divided by 4?",
    correct_answer: "25",
    incorrect_answers: ["20", "30", "40"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 15% of 200?",
    correct_answer: "30",
    incorrect_answers: ["25", "35", "40"],
    category: "Math",
    difficulty: "medium",
  },
  {
    question: "If x + 3 = 10, what is the value of x?",
    correct_answer: "7",
    incorrect_answers: ["6", "5", "8"],
    category: "Math",
    difficulty: "medium",
  },
  {
    question: "What is the value of π (pi) rounded to 2 decimal places?",
    correct_answer: "3.14",
    incorrect_answers: ["3.13", "3.15", "3.12"],
    category: "Math",
    difficulty: "medium",
  },
  {
    question: "Solve for x: 2x - 4 = 10",
    correct_answer: "7",
    incorrect_answers: ["6", "8", "5"],
    category: "Math",
    difficulty: "medium",
  },
  {
    question: "What is the derivative of x²?",
    correct_answer: "2x",
    incorrect_answers: ["x", "x²", "1"],
    category: "Math",
    difficulty: "hard",
  },
  {
    question: "What is the integral of 2x dx?",
    correct_answer: "x² + C",
    incorrect_answers: ["2x + C", "x²", "2x² + C"],
    category: "Math",
    difficulty: "hard",
  },
  {
    question: "What is the limit of (1/x) as x approaches infinity?",
    correct_answer: "0",
    incorrect_answers: ["1", "Infinity", "Undefined"],
    category: "Math",
    difficulty: "hard",
  },
  {
    question:
      "What is the result of the determinant of a 2x2 matrix [[1,2],[3,4]]?",
    correct_answer: "-2",
    incorrect_answers: ["2", "1", "0"],
    category: "Math",
    difficulty: "hard",
  },
  {
    question: "What is the next prime number after 29?",
    correct_answer: "31",
    incorrect_answers: ["33", "35", "37"],
    category: "Math",
    difficulty: "medium",
  },
  {
    question: "Which number is a perfect cube?",
    correct_answer: "27",
    incorrect_answers: ["20", "25", "30"],
    category: "Math",
    difficulty: "medium",
  },
  {
    question: "What is 12 squared?",
    correct_answer: "144",
    incorrect_answers: ["124", "154", "134"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 5 + 7?",
    correct_answer: "12",
    incorrect_answers: ["10", "11", "13"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 9 - 4?",
    correct_answer: "5",
    incorrect_answers: ["4", "6", "7"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 6 x 6?",
    correct_answer: "36",
    incorrect_answers: ["30", "42", "32"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "What is 81 ÷ 9?",
    correct_answer: "9",
    incorrect_answers: ["8", "7", "6"],
    category: "Math",
    difficulty: "easy",
  },
  {
    question: "How many sides does a hexagon have?",
    correct_answer: "6",
    incorrect_answers: ["5", "7", "8"],
    category: "Math",
    difficulty: "easy",
  },
];
